/*
 * i2c.c
 *
 *  Created on: 24 de set. de 2026
 *      Author: Antonio Thomaz
 */

#include "stm32l4xx.h"

/*
 * PA9: I2C1_SCL (alternate function 4)
 * PA10: I2C1_SDA, (alternate function 4)
 * Pin assignment:
 * PA9 (stm32) -> D1 (Arduino Nano)
 * PA10 (stm32) -> D0 (Arduino Nano)
 * */

void I2C1_init(void){

	// Enable clock access to GPIOA
	RCC->AHB2ENR |= RCC_AHB2ENR_GPIOAEN;

	// Set PA9 and PA10 to alternate function mode (10)
	GPIOA->MODER &= ~(1U << 18);
	GPIOA->MODER |= (1U << 19);
	GPIOA->MODER &= ~(1U << 20);
	GPIOA->MODER |= (1U << 21);

	// Set PA9 to I2C1_SCL alternate function
	GPIOA->AFR[1] &= ~(0xFU << GPIO_AFRH_AFSEL9_Pos);
	GPIOA->AFR[1] |= (4U << GPIO_AFRH_AFSEL9_Pos);

	// Set PA10 to I2C1_SDA alternate function
	GPIOA->AFR[1] &= ~(0XFU << GPIO_AFRH_AFSEL10_Pos);
	GPIOA->AFR[1] |= (4U << GPIO_AFRH_AFSEL10_Pos);

	// Set PA9 and PA10 output type to open drain
	GPIOA->OTYPER |= GPIO_OTYPER_OT9;
	GPIOA->OTYPER |= GPIO_OTYPER_OT10;

	// Enable Pullup for PA9 and PA10 (01)
	GPIOA->PUPDR |= GPIO_PUPDR_PUPD9_0;
	GPIOA->PUPDR &= ~GPIO_PUPDR_PUPD9_1;
	GPIOA->PUPDR |= GPIO_PUPDR_PUPD10_0;
	GPIOA->PUPDR &= ~GPIO_PUPDR_PUPD10_1;

	// Enable clock access to I2C1
	RCC->APB1ENR1 |= RCC_APB1ENR1_I2C1EN;

	// Get from CubeMX's I2C parameter panel
	I2C1->TIMINGR = 0x00B07CB4;

	// Enable I2C1 module
	I2C1->CR1 |= I2C_CR1_PE;

}

void I2C1_byteRead(char saddr, char maddr, char* data){

	// Wait until bus is not busy
	while(I2C1->ISR & I2C_ISR_BUSY){}

	// Configure: slave address, write direction, 1 byte, software end
	I2C1->CR2 = 0;
	I2C1->CR2 |= ((uint32_t)saddr << 1) & I2C_CR2_SADD_Msk;
	I2C1->CR2 |= (1U << I2C_CR2_NBYTES_Pos);
	I2C1->CR2 &= ~I2C_CR2_RD_WRN; // write
	I2C1->CR2 &= ~I2C_CR2_AUTOEND;

	// Generate start
	I2C1->CR2 |= I2C_CR2_START;

	// Wait until ready to transmit
	while(!(I2C1->ISR & I2C_ISR_TXIS)){}

	// Send memory address
	I2C1->TXDR = maddr;

	// Wait until transfer complete (NBYTES reached, SCL held low)
	while(!(I2C1->ISR & I2C_ISR_TC)){}

	// Reconfigure: same address, read direction, 1 byte, auto-end
	// Hardware will auto-NACK this byte since it's the last one, then auto-STOP
	I2C1->CR2 = 0;
	I2C1->CR2 |= ((uint32_t)saddr << 1) & I2C_CR2_SADD_Msk;
	I2C1->CR2 |= (1U << I2C_CR2_NBYTES_Pos);
	I2C1->CR2 |= I2C_CR2_RD_WRN; // read
	I2C1->CR2 |= I2C_CR2_AUTOEND;

	// Generate repeated start
	I2C1->CR2 |= I2C_CR2_START;

	// Wait until data received
	while(!(I2C1->ISR & I2C_ISR_RXNE)){}

	// Read data from RXDR
	*data = I2C1->RXDR;

	// Wait for stop condition (auto-generated by hardware since AUTOEND = 1)
	while(!(I2C1->ISR & I2C_ISR_STOPF)){}

	// Clear STOP flag
	I2C1->ICR |= I2C_ICR_STOPCF;
}


void I2C1_burstRead(char saddr, char maddr, int n, char* data){

	// Wait until bus is not busy
	while(I2C1->ISR & I2C_ISR_BUSY){}

	// Write phase: send memory address
	I2C1->CR2 = 0;
	I2C1->CR2 |= ((uint32_t)saddr << 1) & I2C_CR2_SADD_Msk;
	I2C1->CR2 |= (1U << I2C_CR2_NBYTES_Pos);
	I2C1->CR2 &= ~I2C_CR2_RD_WRN; // write
	I2C1->CR2 &= ~I2C_CR2_AUTOEND; // keep control of bus for repeated start

	// Generate start
	I2C1->CR2 |= I2C_CR2_START;

	// Wait until ready to transmit
	while(!(I2C1->ISR & I2C_ISR_TXIS)){}

	// Send memory address
	I2C1->TXDR = maddr;

	// Wait until transfer complete
	while (!(I2C1->ISR & I2C_ISR_TC)){}

	// --- Read phase: read n bytes ---
	I2C1->CR2 = 0;
	I2C1->CR2 |= ((uint32_t)saddr << 1) & I2C_CR2_SADD_Msk;
	I2C1->CR2 |= ((uint32_t)n << I2C_CR2_NBYTES_Pos) & I2C_CR2_NBYTES_Msk;
	I2C1->CR2 |= I2C_CR2_RD_WRN;     // read
	I2C1->CR2 |= I2C_CR2_AUTOEND;    // hardware auto-generates STOP after NBYTES

	// Generate repeated start
	I2C1->CR2 |= I2C_CR2_START;

	// Read n bytes as they arrive
	while(n > 0U){

		// Wait until a byte has been received
		while(!(I2C1->ISR & I2C_ISR_RXNE)){}

		// Read data from RXDR
		*data++ = I2C1->RXDR;

		n--;
	}

	// Wait for STOP condition (auto-generated by hardware since AUTOEND = 1)
	while(!(I2C1->ISR & I2C_ISR_STOPF)){}

	// Clear STOP flag
	I2C1->ICR |= I2C_ICR_STOPCF;
}


void I2C1_burstWrite(char saddr, char maddr, int n, char* data){

	// Wait until bus is not busy
	while(I2C1->ISR & I2C_ISR_BUSY){}

	/* Configure: slave address, write direction, (n+1) bytes total
	(1 for memory address + n data bytes), auto-end */
	I2C1->CR2 = 0;
	I2C1->CR2 |= ((uint32_t)saddr << 1) & I2C_CR2_SADD_Msk;
	I2C1->CR2 |= ((uint32_t)(n + 1) << I2C_CR2_NBYTES_Pos) & I2C_CR2_NBYTES_Msk;
	I2C1->CR2 &= ~I2C_CR2_RD_WRN;    // write
	I2C1->CR2 |= I2C_CR2_AUTOEND;    // hardware auto-generates STOP after NBYTES

	// Generate start
	I2C1->CR2 |= I2C_CR2_START;

	// Wait until ready to transmit
	while (!(I2C1->ISR & I2C_ISR_TXIS)){}

	// Send memory address
	I2C1->TXDR = maddr;

	// Send n data bytes
	for(int i = 0; i < n; i++){

		// Wait until ready to transmit
		while(!(I2C1->ISR & I2C_ISR_TXIS)){}

		I2C1->TXDR = *data++;
	}

	// Wait for STOP condition (auto-generated by hardware since AUTOEND = 1)
	while(!(I2C1->ISR & I2C_ISR_STOPF)){}

	// Clear STOP flag
	I2C1->ICR |= I2C_ICR_STOPCF;
}
